name: MCAdminTools
main: com.norcode.bukkit.mcadmintools.MCAdminTools
version: 0.0.1
commands:
  gamemode:
    aliases: [gmc, gms, gm]
    description: change your or another player's game mode.
    permission: mcadmintools.gamemode
  jump:
    aliases: [j, jumpto]
    description: teleport to the location you are targetting.
    usage: /<command>
    permission: mcadmintools.jump
  xp:
    aliases: [exp, experience]
    description: give/take/set xp or levels.
    usage: /<command> [give|take|set] [<player>] <amount>
  repair:
    usage: /<command>
    description: repairs the item in your hand.
    permission: mcadmintools.repair
  smite:
    usage: /<command> <target>
    description: Strike a player with lightning
    permission: mcadmintools.smite
  splash:
    usage: /<command> [<target>] <potionEffect> [<duration> <amplifier>}
    description: Apply a potion effect to yourself or another player.
    permission: mcadmintools.splash
  heal:
    description: Heal yourself or another player.
    usage: /<command> [<player>]
    permission: mcadmintools.heal
  feed:
    description: feed yourself or another player.
    usage: /<command> [<player>]
    permission: mcadmintools.feed
  dispel:
    aliases: [milk]
    usage: /<command> [<player>]
    description: remove all potion effects from yourself or another player.
    permission: mcadmintools.dispel
  invsee:
    aliases: [viewinv, showinv, seeinv]
    description: show another players inventory.
    permission: mcadmintools.invsee
  enderchest:
    aliases: [endchest]
    description: show another players enderchest inventory.
    permission: mcadmintools.enderchest
  kill:
    description: kill another player.
    usage: /<command> <player>
    permission: mcadmintools.kill
  suicide:
    description: kill yourself.
    usage: /<command>
    permission: mcadmintools.suicide
  workbench:
    description: opens a crafting table.
    usage: /<command>
    permission: mcadmintools.workbench
permissions:
  mcadmintools.gamemode:
    default: false
    description: give access to gamemode command
  mcadmintools.workbench:
    default: false
    description: gives access to workbench command
  mcadmintools.xp.set:
    default: false
    description: gives access to set own xp.
  mcadmintools.xp.give:
    default: false
    description: gives access to give yourself xp.
  mcadmintools.xp.take:
    default: false
    description: gives access to take xp from yourself.
  mcadmintools.xp.set.others:
    default: false
    description: gives access to set another player's xp.
  mcadmintools.xp.give.others:
    default: false
    description: gives access to give another player xp.
  mcadmintools.xp.take.others:
    default: false
    description: gives access to take xp from another player.
  mcadmintools.enderchest:
    default: false
    description: gives access to 'enderchest'.
  mcadmintools.invsee:
    default: false
    description: gives access to 'invsee'.
  mcadmintools.dispel:
    default: false
    description: gives access to 'dispel'.
  mcadmintools.suicide:
    default: false
    description: gives access to 'suicide'.
  mcadmintools.kill:
    default: false
    description: gives access to 'kill'.
  mcadmintools.heal:
    default: false
    description: gives access to 'heal'.
  mcadmintools.feed:
    default: false
    description: gives access to 'feed'.
  mcadmintools.admin:
    default: op
    description: gives the access to all commands.
    children: 
        mcadmintools.heal: true
        mcadmintools.feed: true
        mcadmintools.kill: true
        mcadmintools.suicide: true
        mcadmintools.dispel: true
        mcadmintools.invsee: true
        mcadmintools.enderchest: true
        mcadmintools.xp.set: true
        mcadmintools.xp.set.others: true
        mcadmintools.xp.give: true
        mcadmintools.xp.give.others: true
        mcadmintools.xp.take: true
        mcadmintools.xp.take.others: true
        mcadmintools.workbench: true
        mcadmintools.splash: true
        mcadmintools.smite: true
        mcadmintools.repair: true
        mcadmintools.jump: true
        mcadmintools.gamemode: true