votifier-commands:
  - "broadcast thanks for the vote __name__."

cook-mappings:
    PORK: GRILLED_PORK
    RAW_FISH: COOKED_FISH
    POTATO_ITEM: BAKED_POTATO
    RAW_BEEF: COOKED_BEEF
    RAW_CHICKEN: COOKED_CHICKEN
    SAND: GLASS
    COBBLESTONE: STONE
    IRON_ORE: IRON_INGOT
    GOLD_ORE: GOLD_INGOT
    LOG: "COAL:1"
    DIAMOND_ORE: DIAMOND
    EMERALD_ORE: EMERALD
    REDSTONE_ORE: REDSTONE
    LAPIS_ORE: "INK_SACK:4"
    CACTUS: "INK_SACK:2"
    CLAY_BALL: CLAY_BRICK
    NETHERRACK: NETHER_BRICK_ITEM
    NETHER_QUARTZ_ORE: NETHER_QUARTZ
