name: MCAdminTools
main: com.norcode.bukkit.mcadmintools.MCAdminTools
version: 0.0.1
softdepend: [Votifier]

commands:
  mcadmintools:
    usage: /<command> reloadconfig
    description: reload the config file
    permission: mcadmintools.admin
  fly:
    usage: /<command> [<player>]
    description: Toggle flight
    permission: mcadmintools.fly
  spawn:
    usage: /<command>
    description: Teleports the player to the server's spawn point.
    permission: mcadmintools.spawn
  setspawn:
    usage: /<command>
    description: Sets the spawn point of the current world to the players current location.
    permission: mcadmintools.setspawn
  give:
    usage: /<command> <player> <material> [<qty>]
    description: Give items.
    permission: mcadmintools.give
  gamemode:
    aliases: [gmc, gms, gm]
    description: change your or another player's game mode.
    permission: mcadmintools.gamemode
  jump:
    aliases: [j, jumpto]
    description: teleport to the location you are targetting.
    usage: /<command>
    permission: mcadmintools.jump
  xp:
    aliases: [exp, experience]
    description: give/take/set xp or levels.
    usage: /<command> [give|take|set] [<player>] <amount>
  cook:
    aliases: [smelt]
    description: cooks or smelts the selected item
    usage: /<command>
    permission: mcadmintools.cook
  more:
    description: Maxes the stack size of the current item.
    usage: /<command>
    permission: mcadmintools.more
  repair:
    usage: /<command>
    description: repairs the item in your hand.
    permission: mcadmintools.repair
  smite:
    usage: /<command> <target>
    description: Strike a player with lightning
    permission: mcadmintools.smite
  splash:
    usage: /<command> [<target>] <potionEffect> [<duration> <amplifier>}
    description: Apply a potion effect to yourself or another player.
    permission: mcadmintools.splash
  heal:
    description: Heal yourself or another player.
    usage: /<command> [<player>]
    permission: mcadmintools.heal
  feed:
    description: feed yourself or another player.
    usage: /<command> [<player>]
    permission: mcadmintools.feed
  dispel:
    aliases: [milk]
    usage: /<command> [<player>]
    description: remove all potion effects from yourself or another player.
    permission: mcadmintools.dispel
  invsee:
    aliases: [viewinv, showinv, seeinv]
    description: show another players inventory.
    permission: mcadmintools.invsee
  enderchest:
    aliases: [endchest]
    description: show another players enderchest inventory.
    permission: mcadmintools.enderchest
  kill:
    description: kill another player.
    usage: /<command> <player>
    permission: mcadmintools.kill
  suicide:
    description: kill yourself.
    usage: /<command>
    permission: mcadmintools.suicide
  workbench:
    description: opens a crafting table.
    usage: /<command>
    permission: mcadmintools.workbench
  enchant:
    aliases: [mcenchant]
    description: enchants the item in hand with the given enchantments.
    usage: /<command> [[<enchantment> <level>] ...]
    permission: mcadmintools.enchant
  broadcast:
    aliases: [announce]
    permission: mcadmintools.broadcast
    usage: /<command> <message>
    description: broadcast a message to all users on the server.
  flyspeed:
    aliases: [fspeed]
    description: adjust flight speed
    usage: /<command> [1-5]
    permission: mcadmintools.flyspeed
  playerhead:
    aliases: [phead]
    description: spawn a players head
    usage: /<command> <headOwner> <receiver>
    permission: mcadmintools.playerhead
permissions:
  mcadmintools.fly:
    default: op
    description: allow flight
  mcadmintools.fly.others:
    default: op
    description: allow giving flight to others.
  mcadmintools.spawn:
    default: true
    description: give access to spawn command
  mcadmintools.spawn.others:
    default: op
    description: give access to send others to spawn
  mcadmintools.setspawn:
    default: false
    description: give access to setspawn command
  mcadmintools.enchant:
    default: false
    description: give access to enchant command
  mcadmintools.gamemode:
    default: false
    description: give access to gamemode command
  mcadmintools.workbench:
    default: false
    description: gives access to workbench command
  mcadmintools.more:
    default: false
    description: Increase quantity of the item stack in hand.
  mcadmintools.xp.set:
    default: false
    description: gives access to set own xp.
  mcadmintools.xp.give:
    default: false
    description: gives access to give yourself xp.
  mcadmintools.xp.take:
    default: false
    description: gives access to take xp from yourself.
  mcadmintools.xp.set.others:
    default: false
    description: gives access to set another player's xp.
  mcadmintools.xp.give.others:
    default: false
    description: gives access to give another player xp.
  mcadmintools.xp.take.others:
    default: false
    description: gives access to take xp from another player.
  mcadmintools.enderchest:
    default: false
    description: gives access to 'enderchest'.
  mcadmintools.invsee:
    default: false
    description: gives access to 'invsee'.
  mcadmintools.dispel:
    default: false
    description: gives access to 'dispel'.
  mcadmintools.suicide:
    default: false
    description: gives access to 'suicide'.
  mcadmintools.kill:
    default: false
    description: gives access to 'kill'.
  mcadmintools.heal:
    default: false
    description: gives access to 'heal'.
  mcadmintools.feed:
    default: false
    description: gives access to 'feed'.
  mcadmintools.cook:
    default: false
    description: gives access to 'cook'.
  mcadmintools.flyspeed:
    default: false
    description: gives access to 'flyspeed'
  mcadmintools.broadcast:
    default: op
    description: gives access to 'broadcast'
  mcadmintools.playerhead:
    default: op
    description: gives access to 'playerhead' command
  mcadmintools.admin:
    default: op
    description: gives the access to all commands.
    children: 
        mcadmintools.heal: true
        mcadmintools.feed: true
        mcadmintools.kill: true
        mcadmintools.suicide: true
        mcadmintools.dispel: true
        mcadmintools.invsee: true
        mcadmintools.enderchest: true
        mcadmintools.enchant: true
        mcadmintools.xp.set: true
        mcadmintools.xp.set.others: true
        mcadmintools.xp.give: true
        mcadmintools.xp.give.others: true
        mcadmintools.xp.take: true
        mcadmintools.xp.take.others: true
        mcadmintools.workbench: true
        mcadmintools.splash: true
        mcadmintools.smite: true
        mcadmintools.repair: true
        mcadmintools.jump: true
        mcadmintools.gamemode: true
        mcadmintools.more: true
        mcadmintools.cook: true
        mcadmintools.setspawn: true
        mcadmintools.spawn: true
        mcadmintools.flyspeed: true
        mcadmintools.broadcast: true
        mcadmintools.playerhead: true